---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-endeca-mdex-6.5.1
    image: centos:6
    groups:
      - endeca_mdex_6.5.1
  - name: test-endeca-mdex-6.5.2
    image: centos:6
    groups:
      - endeca_mdex_6.5.2
provisioner:
  name: ansible
  config_options:
    ssh_connection:
      control_path: "/var/ans/%%h"
  lint:
    name: ansible-lint
scenario:
  name: docker-6.5.x
verifier:
  name: testinfra
  lint:
    name: flake8
